server:
  port: 9901

  
spring:
  application:
    name: configtest-prod
  config:
    import:
    - optional:configserver:http://localhost:9900

management:
  endpoints:
    web:
      exposure:
        include:
        - refresh